### ISSUE TITLE
Upgrade to Laravel v6.0

### ISSUE THREAD

**Issue by hopeseekr** [PHPExpertsInc/laravel_quickstart#15]

**Comment by peter279k** [comment]
It seems that this quick start has the `Laravel 7.x` at least on `master` branch.

Maybe we can consider releasing version with `git tag` to resolve this issue?

**Comment by hopeseekr** [comment]
Hi @peter279k> i've seen you all over the place, including several of my repos! I truly respect you as a person!

I released Laravel 7.0 support for this project 25 days ago on July 9th. It is of the tag [v1.2.0+php7.4+laravel7.0](https://github.com/phpexpertsinc/laravel_quickstart/tree/v1.2.0+php7.4+laravel7.0).

I'm not sure if that is compatible with packagist.org, but I don't think even has a packagist.org package, tho, in retrospect, I guess that's pretty dumb. I always just `git clone` it.

I always pretty much figured I was the only one using this project until your comment.

**Comment by hopeseekr** [comment]
If you want to see a project that is directly based off this project, check out: https://github.com/CovidResearch/ems.covidreporter.news
